 ENV['SPREEDLYCORE_API_LOGIN'] = 'ZCqlTGZYtZQesf5Zodny9jtQwj3'
 ENV['SPREEDLYCORE_API_SECRET'] = 'Pmrm06fqq4pGrgF3a83OFq1oB6boINInoxtV6pC5mvx7fj0P6KUm0iPLDtFoqv4J'
 ENV['SPREEDLYCORE_API_GATEWAY_TOKEN'] = 'UQEekp5WXw39UqvI08rA297WxzC'


# Non-Heroku Version - YOU GOT THIS WORKING 
# ENV['SPREEDLYCORE_API_LOGIN'] = 'PKAJFXgRvJbgXxaJweC6tpgwF62'
# ENV['SPREEDLYCORE_API_SECRET'] = 'skN9EwWEuZlG8i6XzHKXLkUT5TmqwsytKXzsI0DBy7Dsb4zpPbTc0EOz4jQ9zMx2'
# ENV['SPREEDLYCORE_API_GATEWAY_TOKEN'] = '8R5xuOEMJvho0uLgyjac2GbUpGu'

SpreedlyCore.configure #(:api_login => 'ZCqlTGZYtZQesf5Zodny9jtQwj3', :api_secret => 'Pmrm06fqq4pGrgF3a83OFq1oB6boINInoxtV6pC5mvx7fj0P6KUm0iPLDtFoqv4J' )
